### ISSUE TITLE
Seems like its not working anymore

### ISSUE THREAD

**Issue by PySualk** [javaguirre/twitter-streaming-api-example#1]
Hey there,

after cloning the project I ran _npm install_ and _bower install_. When I tried to login via Twitter the following error occured:

``` javascript
 Error: Desktop applications only support the oauth_callback value 'oob'
    at Strategy.parseErrorResponse (/home/****/node_workspace/twitter-streaming-api-example/node_modules/passport-twitter/lib/strategy.js:182:10)
    at Strategy.OAuthStrategy._createOAuthError (/home/****/node_workspace/twitter-streaming-api-example/node_modules/passport-oauth1/lib/strategy.js:349:16)
    at /home/****/node_workspace/twitter-streaming-api-example/node_modules/passport-oauth1/lib/strategy.js:218:41
    at /home/****/node_workspace/twitter-streaming-api-example/node_modules/oauth/lib/oauth.js:543:17
    at passBackControl (/home/****/node_workspace/twitter-streaming-api-example/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/home/****/node_workspace/twitter-streaming-api-example/node_modules/oauth/lib/oauth.js:409:9)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
```

**Comment by javaguirre** [comment]
I think this is could be fixed with an upgrade of a package, related:

https://twittercommunity.com/t/desktop-applications-only-support-the-oauth-callback-value-oob-oauth-request-token/252
